### PR TITLE
Improve type safety.

### PR DESCRIPTION
**Pull request by player-03**

### CODE REVIEW

**Comment by gcardozo123** [comment]
Hi, @player-03. I'll take a look into your pull request later today. Thanks for contributing!

**Comment by gcardozo123** [comment]
@player-03 your PL produces:
`simpleECS/Entity.hx:11: characters 33-42 : Invalid number of type parameters for simpleECS.Component`
`simpleECS/Component.hx:7: characters 18-27 : Invalid number of type parameters for simpleECS.Component`

**Comment by player-03** [comment]
Pretty sure that will do it, but you'll still have to test.

**Comment by gcardozo123** [comment]
Thanks again @player-03, I'll test it later today!

**Comment by gcardozo123** [comment]
@player-03 now, this is the result:
`simpleECS/Entity.hx:55: characters 16-35 : Class<getComponent.T> should be Class<simpleECS.Component>`
`/simpleECS/Entity.hx:55: characters 16-35 : Type parameters are invariant`
`/simpleECS/Entity.hx:55: characters 16-35 : getComponent.T should be simpleECS.Component`
`/simpleECS/Entity.hx:56: characters 16-24 : simpleECS.Component should be getComponent.T`

**Comment by player-03** [comment]
This time I tested it, using the code provided in README.md.

**Comment by gcardozo123** [comment]
Cool, this time the build passed! I'll take a closer look on it this weekend, I also intend to do some more improvements to this repo.
Thanks!

**Pull request merged**
